name: laravel-unit-tests
on:
  workflow_call: # Indicates that this is a reusable workflow
    inputs: # Defines the inputs that can be passed from the caller workflow
      php-version: # Name of the input
        required: true # Specifies that this input is mandatory
        type: string # Specifies the type of the input
    # secrets: # Defines the secrets that can be passed from the caller workflow
    #   envPAT: # Name of the secret
    #     required: true # Specifies that this secret is mandatory

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version}}
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Configure the project
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate
          php artisan config:clear
      - name: Run tests
        run: php artisan test
