name: mysql-service
on: push

jobs:
  default-mysql:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: root

    steps:
      - uses: actions/checkout@v4
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - name: MySQL version
        run: mysql -uroot -p${{ env.DB_PASSWORD }} -e "SELECT VERSION();"
      - name: Use database
        run: |
          mysql -uroot -p${{ env.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS test;"
          mysql -uroot -p${{ env.DB_PASSWORD }} -e "USE test; CREATE TABLE IF NOT EXISTS users (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, PRIMARY KEY (id));"
          mysql -uroot -p${{ env.DB_PASSWORD }} -e "USE test; INSERT INTO users (name) VALUES ('Alice');"
          mysql -uroot -p${{ env.DB_PASSWORD }} -e "USE test; INSERT INTO users (name) VALUES ('Bob');"
          mysql -uroot -p${{ env.DB_PASSWORD }} -e "USE test; SELECT * FROM users;"
