name: Mysql Service
on: push

jobs:
  default-mysql:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: root
      MYSQL_DATABASE: test_gh_actions

    steps:
      - uses: actions/checkout@v4
      - name: Configure MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -p${{ env.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.MYSQL_DATABASE }};"
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: php artisan test
