name: unit-tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none
      - name: check php version
        run: php -v
      - name: install dependencies
        run: composer install --prefer-dist
      - name: run test suite
        run: vendor/bin/phpunit test
